### ISSUE TITLE
Still under active development?

### ISSUE THREAD

**Issue by CrashAndSideburns** [simensgreen/rusymbols#1]
Sorry if this is considered a rude way to get in contact, but is this crate still under development? I'm new-ish to Rust, but I'm interested in Symbolic Computation, so I'd love to be involved.

**Comment by simensgreen** [comment]
Yes, this crate is still under development, but you'd better not rely on this crate for now, since I'm still looking for optimal tools and techniques for working with symbolic computation in Rust.

**Comment by CrashAndSideburns** [comment]
Okay, cool. Thanks for the info and good luck!
